# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=100)),
                ('db_name', models.CharField(max_length=20)),
                ('table_name', models.CharField(max_length=50)),
                ('file_dir', models.CharField(max_length=50)),
                ('static_column', models.CharField(max_length=100)),
                ('error_alarm', models.CharField(max_length=10)),
                ('date_week', models.CharField(max_length=100)),
                ('date_alarm', models.CharField(max_length=10)),
                ('owner', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('valid_flag', models.CharField(max_length=50)),
            ],
        ),
    ]
