# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqc', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_pass', models.CharField(max_length=20)),
                ('is_admin', models.BigIntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
